project:
  type: website

website:
  site-url: https://iqb-berlin.github.io/coding-info/
  title: "coding-info"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-berlin/coding-info/
  repo-actions: [issue]
  navbar:
    pinned: true
    search: true
    logo: IQB-klein.png
  page-footer:
    background: light
    right:
      - text: "IQB 2024"
        href: https://www.iqb.hu-berlin.de
    left:
      - text: "{{< fa house >}}"
        href: index.qmd
      - icon: github
        href: https://github.com/iqb-berlin/coding-info
  sidebar: 
    style: "docked"
    search: true
    lang: de
    contents:
      - href: index.qmd
        text: Start
      - href: introduction/index.qmd
        text: Einführung
      - section: Datenstrukturen
        href: data-structures/index.qmd
        contents:
          - href: data-structures/response.qmd
            text: Antwort/Variable
          - data-structures/coding-scheme.qmd
          - section: itc-ToolBox Output
            href: data-structures/itc-ToolBox-Output/index.qmd
            contents:
              - href: data-structures/itc-ToolBox-Output/tc-merge.qmd
                text: "Format TC-Merge"
      - section: Kodierung
        href: coding/index.qmd
        contents:
          - coding/valid-responses.qmd
          - coding/derive.qmd
          - coding/missings.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
