project:
  type: website

website:
  site-url: https://iqb-berlin.github.io/coding-info/
  title: "Coding-info"
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-berlin/coding-info/
  repo-actions: [issue]
  navbar:
    search: true
    logo: IQB-klein.png
  page-footer:
    background: light
    right:
      - text: "IQB 2024"
        href: https://www.iqb.hu-berlin.de
    left:
      - icon: IQB-klein.png
        href: index.qmd
  sidebar: 
    style: "docked"
    search: true
    lang: de
    contents:
      - href: index.qmd
        text: Start

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    anchor-sections: true
    link-external-icon: true
    link-external-newwindow: true
